name: checks
on: [push, pull_request]
jobs:
  check:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: ['3.12', '3.13', '3.14']
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true
          python-version: ${{ matrix.python }}
      - run: uv sync --locked
      - run: uv run --locked ruff check .
      - run: uv run --locked ruff format --check .
      - run: uv run --locked ty check
      - run: uv run --locked python -m unittest discover -v
      - run: uv build
